language: node_js

deploy:
  provider: script
  script: curl -T index.html sftp://${FTP_USER}:${FTP_PASSWORD}@${FTP_HOST}/www
  on:
    branch: master

script: sftp ${FTP_USER}:${FTP_PASSWORD}@${FTP_HOST}:/www/index.html index.html
