language: node_js

addons:
  apt:
    packages:
    - sshpass

deploy:
  provider: script
  script: curl -T index.html sftp://${FTP_USER}:${FTP_PASSWORD}@${FTP_HOST}/www
  on:
    branch: master

script:
  - echo yes | sftp ${FTP_USER}@${FTP_HOST}:/www/index.html index.html
