language: node_js

node_js:
  - "10"

before_install:
  - npm i -g firebase-tools

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: add-firebase-deploy-7

script:
  - echo Hello