language: node_js

install:
  - echo $FTP_HOST >> $HOME/.ssh/known_hosts
  - cat $HOME/.ssh/known_hosts

deploy:
  provider: script
  script: curl -T index.html sftp://${FTP_USER}:${FTP_PASSWORD}@${FTP_HOST}/www
  on:
    branch: master

script: sftp -o StrictHostKeyChecking=no ${FTP_USER}:${FTP_PASSWORD}@${FTP_HOST}:/www/index.html index.html
